version: '3'
services:
  app:
    build: .
    container_name: getintouch
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - ./admin.sdk.json:/usr/src/app/admin.sdk.json
    networks:
      - getintouch-network

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ever
    volumes:
      - mongo-data:/data/db
    networks:
      - getintouch-network

volumes:
  mongo-data:

networks:
  getintouch-network:
    driver: bridge
